name: Cross Compile C

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: env
        run: echo $GITHUB_WORKSPACE

      - name: cmake generate
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && cmake ..

      - name: cmake build
        run: cd $GITHUB_WORKSPACE/build && cmake --build . --config Release

      - name: ls build files
        run: cd $GITHUB_WORKSPACE/build && pwd && ls -alh

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: $GITHUB_WORKSPACE/build/
