name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build APK
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ./app/build/outputs/apk/
